var RRResourcesText = {
	search_placeholder:"Hvad søger du?",
	current_connect_placeholder:"Hvad vil du fortælle?",
	main_nav_current:"Aktuelt",
	main_nav_colleagues:"Kolleger",
	main_nav_mycompany:"Min virksomhed",
	main_nav_royalreesink:"Royal Reesink",
	current_messages_heading:"Aktuelt",
	current_messages_load_more:"Download beskeder",
	current_connect_heading:"Connect",
	current_connect_send:"Post a message on Yammer",
	current_connect_others:"What others are saying:",
	current_workfor_heading:"Arbejde hos",
	current_vacancies_more:"Se alle jobs",
	current_filter:"Filter on:",
	companyprofile_events:"Arrangementer",
	companyprofile_alldayevent:"Arrangement varer hele dagen",
	companyprofile_events_more:"Se alle arrangementer",
	companyprofile_employees:"Hvem arbejder i denne virksomhed",
	companyprofile_google_maps:"Beregn rute på google maps",
	companyprofile_locations_search:"søg lokation...",
	companyprofile_no_locations:"ingen lokation fundet",
	companyprofile_no_events:"intet arrangement fundet",
	companyprofile_profile:"Profil",
	companyprofile_read_more:"Læs mere",
	event_company:"Virksomhed",
	event_location:"Lokation",
	event_date:"Dato",
	event_startdate:"Begyndelsestid",
	event_enddate:"Sluttid",
	event_website:"Webside",
	event_image:"Billede",
	event_description:"Beskrivelse",
	event_organizer:"Organisator",
	user_profile_company:"Virksomhed",
	user_profile_location:"Lokation",
	user_profile_jobtitle:"Stilling",
	user_profile_department:"Afdeling",
	user_profile_workdays:"Arbejdsdage",
	user_profile_expertise:"Ekspertise",
	user_profile_aboutme:"Biografi",
	user_profile_sharedby:"Delt af",
	user_profile_phone_short:"T",
	user_profile_fax_short:"F",
	user_profile_email_short:"E",
	user_profile_discover:"opdag mere i Delve...",
	news_contactperson:"Kontaktperson",
	companyarticle_view_also:"Se også",
	companyarticle_documents:"Dokumenter",
	companyarticle_events:"Events",
	search_searchresult:"Search results",
	search_filterresult:"Filter results",
	comments_heading:"Comments",
	comments_enter_comment:"Place your comment",
	comments_description_placeholder:"Write a comment",
	comments_not_enabled:"comments are not enabled for this article",
	main_nav_menu:"Menu"
};
