var RRResourcesText = {
	search_placeholder:"Что Вы ищите?",
	current_connect_placeholder:"Что Вы хотите рассказать?",
	main_nav_current:"Актуально",
	main_nav_colleagues:"Коллеги",
	main_nav_mycompany:"Мое предприятие",
	main_nav_royalreesink:"Royal Reesink",
	current_messages_heading:"Актуально",
	current_messages_load_more:"Загрузить больше сообщений…",
	current_connect_heading:"Подключить",
	current_connect_send:"Post a message on Yammer",
	current_connect_others:"What others are saying:",
	current_workfor_heading:"Работать в",
	current_vacancies_more:"Посмотреть все вакансии",
	current_filter:"Filter on:",
	companyprofile_events:"События",
	companyprofile_alldayevent:"Событие проходит целый день",
	companyprofile_events_more:"Посмотреть все события",
	companyprofile_employees:"Кто работает на этом предприятии",
	companyprofile_google_maps:"Проложить маршрут на карте Google",
	companyprofile_locations_search:"Поиск по местоположению ...",
	companyprofile_no_locations:"Не найдено ни одного местоположения",
	companyprofile_no_events:"Не найдено ни одного события",
	companyprofile_profile:"Профиль",
	companyprofile_read_more:"Читать далее",
	event_company:"Предприятие",
	event_location:"Местоположение",
	event_date:"Дата",
	event_startdate:"Время начала",
	event_enddate:"Время окончания",
	event_website:"Веб-сайт",
	event_image:"Изображение",
	event_description:"Описание",
	event_organizer:"Организатор",
	user_profile_company:"Предприятие",
	user_profile_location:"Местоположение",
	user_profile_jobtitle:"Должность",
	user_profile_department:"Отдел",
	user_profile_workdays:"Рабочие дни",
	user_profile_expertise:"Заключение",
	user_profile_aboutme:"Биография",
	user_profile_sharedby:"Поделился",
	user_profile_phone_short:"P",
	user_profile_fax_short:"F",
	user_profile_email_short:"E",
	user_profile_discover:"узнать больше в Delve ...",
	news_contactperson:"Контактное лицо",
	companyarticle_view_also:"Просмотреть также",
	companyarticle_documents:"Документы",
	companyarticle_events:"События",
	search_searchresult:"Search results",
	search_filterresult:"Filter results",
	comments_heading:"Comments",
	comments_enter_comment:"Place your comment",
	comments_description_placeholder:"Write a comment",
	comments_not_enabled:"comments are not enabled for this article",
	main_nav_menu:"Menu"
};
