var RRResourcesText = {
	search_placeholder:"Wie of wat zoek je?",
	current_connect_placeholder:"Wat wil je vertellen?",
	main_nav_current:"Actueel",
	main_nav_colleagues:"Collega's",
	main_nav_mycompany:"Mijn bedrijf",
	main_nav_royalreesink:"Royal Reesink",
	current_messages_heading:"Actueel",
	current_messages_load_more:"Laad meer berichten ...",
	current_connect_heading:"Connect",
	current_connect_send:"Plaats een bericht in Yammer",
	current_connect_others:"Wat anderen zeggen:",
	current_workfor_heading:"Werken bij",
	current_vacancies_more:"Bekijk alle vacatures",
	current_filter:"Filter op:",
	companyprofile_events:"Evenementen",
	companyprofile_alldayevent:"Evenement duur de hele dag",
	companyprofile_events_more:"Bekijk alle evenementen",
	companyprofile_employees:"Wie werken er bij dit bedrijf",
	companyprofile_google_maps:"Bereken route op google maps",
	companyprofile_locations_search:"zoeken naar locaties ...",
	companyprofile_no_locations:"geen locaties gevonden",
	companyprofile_no_events:"geen evenementen gevonden",
	companyprofile_profile:"Profiel",
	companyprofile_read_more:"Meer lezen",
	event_company:"Bedrijf",
	event_location:"Locatie",
	event_date:"Datum",
	event_startdate:"Begintijd",
	event_enddate:"Eindtijd",
	event_website:"Website",
	event_image:"Afbeelding",
	event_description:"Omschrijving",
	event_organizer:"Organisator",
	user_profile_company:"Bedrijf",
	user_profile_location:"Locatie",
	user_profile_jobtitle:"Functie",
	user_profile_department:"Afdeling",
	user_profile_workdays:"Werkdagen",
	user_profile_expertise:"Expertise",
	user_profile_aboutme:"Biografie",
	user_profile_sharedby:"Gedeeld door",
	user_profile_phone_short:"T",
	user_profile_fax_short:"F",
	user_profile_email_short:"E",
	user_profile_discover:"ontdek meer in Delve ...",
	news_contactperson:"Contactpersoon",
	companyarticle_view_also:"Bekijk ook",
	companyarticle_documents:"Documenten",
	companyarticle_events:"Evenementen",
	search_searchresult:"Zoekresultaten",
	search_filterresult:"Filter resultaten",
	comments_heading:"Reacties",
	comments_enter_comment:"Plaats je reactie",
	comments_description_placeholder:"Schrijf een reactie",
	comments_not_enabled:"reacties zijn niet ingeschakeld voor dit artikel",
	main_nav_menu:"Menu",
	current_connect_connect_first:"inloggen Yammer",
	current_connect_loading:"berichten laden ..."
};
