var RRResourcesText = {
	search_placeholder:"Que recherchez-vous ?",
	current_connect_placeholder:"Que désirez-vous raconter ?",
	main_nav_current:"Actualités",
	main_nav_colleagues:"Collègues",
	main_nav_mycompany:"Mon Entreprise",
	main_nav_royalreesink:"Royal Reesink",
	current_messages_heading:"Actualités",
	current_messages_load_more:"Chargez davantage de messages...",
	current_connect_heading:"Se connecter",
	current_connect_send:"Post a message on Yammer",
	current_connect_others:"What others are saying:",
	current_workfor_heading:"Travailler à",
	current_vacancies_more:"Consulter toutes les annonces d’emploi",
	current_filter:"Filter on:",
	companyprofile_events:"Évènements",
	companyprofile_alldayevent:"Évènement à la journée",
	companyprofile_events_more:"Consulter tous les évènements",
	companyprofile_employees:"Qui travaille pour cette entreprise",
	companyprofile_google_maps:"Calculer l’itinéraire sur Google Maps",
	companyprofile_locations_search:"rechercher des sites...",
	companyprofile_no_locations:"aucun site trouvé",
	companyprofile_no_events:"aucun évènement trouvé",
	companyprofile_profile:"Profil",
	companyprofile_read_more:"Lire la suite",
	event_company:"Entreprise",
	event_location:"Site",
	event_date:"Date",
	event_startdate:"Horaire de début",
	event_enddate:"Horaire de fin",
	event_website:"Site internet",
	event_image:"Illustration",
	event_description:"Description",
	event_organizer:"Organisateur",
	user_profile_company:"Entreprise",
	user_profile_location:"Site",
	user_profile_jobtitle:"Fonction",
	user_profile_department:"Département",
	user_profile_workdays:"Jours ouvrés",
	user_profile_expertise:"Expertise",
	user_profile_aboutme:"Biographie",
	user_profile_sharedby:"Partagé par",
	user_profile_phone_short:"P",
	user_profile_fax_short:"F",
	user_profile_email_short:"E",
	user_profile_discover:"discover more in Delve ...",
	news_contactperson:"Contact person",
	companyarticle_view_also:"View also",
	companyarticle_documents:"Documents",
	companyarticle_events:"Events",
	search_searchresult:"Search results",
	search_filterresult:"Filter results",
	comments_heading:"Comments",
	comments_enter_comment:"Place your comment",
	comments_description_placeholder:"Write a comment",
	comments_not_enabled:"comments are not enabled for this article",
	main_nav_menu:"Menu"
};
