var RRResourcesText = {
	search_placeholder:"Ne arıyorsunuz?",
	current_connect_placeholder:"Ne anlatmak istersiniz?",
	main_nav_current:"Güncel",
	main_nav_colleagues:"Meslektaşlar",
	main_nav_mycompany:"Şirketim",
	main_nav_royalreesink:"Royal Reesink",
	current_messages_heading:"Güncel",
	current_messages_load_more:"Başka rapor yükleniyor…",
	current_connect_heading:"Bağlan",
	current_connect_send:"Post a message on Yammer",
	current_connect_others:"What others are saying:",
	current_workfor_heading:"Yanında çalışılan",
	current_vacancies_more:"Bütün iş ilanlarına bak",
	current_filter:"Filter on:",
	companyprofile_events:"Etkinlikler",
	companyprofile_alldayevent:"Etkinlik bütün gün sürüyor",
	companyprofile_events_more:"Bütün etkinliklere bak",
	companyprofile_employees:"Bu şirkette kimler çalışıyor",
	companyprofile_google_maps:"Rotayı Google Haritalar'da hesapla",
	companyprofile_locations_search:"Merkez ara…",
	companyprofile_no_locations:"Merkez bulunamadı",
	companyprofile_no_events:"Etkinlik bulunamadı",
	companyprofile_profile:"Profil",
	companyprofile_read_more:"Devamı",
	event_company:"Şirket",
	event_location:"Merkez",
	event_date:"Tarih",
	event_startdate:"Başlangıç saati",
	event_enddate:"Bitiş saati",
	event_website:"Web sitesi",
	event_image:"Görüntü",
	event_description:"Açıklama",
	event_organizer:"Organizatör",
	user_profile_company:"Şirket",
	user_profile_location:"Merkez",
	user_profile_jobtitle:"İşlev",
	user_profile_department:"Departman",
	user_profile_workdays:"İş günü",
	user_profile_expertise:"Uzmanlık",
	user_profile_aboutme:"Biyografi",
	user_profile_sharedby:"Paylaşan",
	user_profile_phone_short:"P",
	user_profile_fax_short:"F",
	user_profile_email_short:"E",
	user_profile_discover:"Delve'de daha fazlasını keşfet…",
	news_contactperson:"İrtibat kişisi",
	companyarticle_view_also:"Ayrıca görüntüle",
	companyarticle_documents:"Belgeler",
	companyarticle_events:"Etkinlikler",
	search_searchresult:"Search results",
	search_filterresult:"Filter results",
	comments_heading:"Comments",
	comments_enter_comment:"Place your comment",
	comments_description_placeholder:"Write a comment",
	comments_not_enabled:"comments are not enabled for this article",
	main_nav_menu:"Menu"
};
