var RRResourcesText = {
	search_placeholder:"Was suchen Sie?",
	current_connect_placeholder:"Was möchten Sie erzählen?",
	main_nav_current:"Aktuell",
	main_nav_colleagues:"Kollegen",
	main_nav_mycompany:"Mein Betrieb",
	main_nav_royalreesink:"Royal Reesink",
	current_messages_heading:"Aktuell",
	current_messages_load_more:"Weitere Berichte laden…",
	current_connect_heading:"Verbinden",
	current_connect_send:"Post a message on Yammer",
	current_connect_others:"What others are saying:",
	current_workfor_heading:"Arbeiten bei",
	current_vacancies_more:"Alle Stellenangebote anschauen",
	current_filter:"Filter on:",
	companyprofile_events:"Veranstaltungen",
	companyprofile_alldayevent:"Veranstaltung dauert den ganzen Tag",
	companyprofile_events_more:"Alle Veranstaltungen anschauen",
	companyprofile_employees:"Wer arbeitet in diesem Betrieb",
	companyprofile_google_maps:"Route auf Google Maps berechnen",
	companyprofile_locations_search:"nach Standorten suchen…",
	companyprofile_no_locations:"keine Standorte gefunden",
	companyprofile_no_events:"keine Veranstaltungen gefunden",
	companyprofile_profile:"Profil",
	companyprofile_read_more:"Mehr lesen",
	event_company:"Betrieb",
	event_location:"Standort",
	event_date:"Datum",
	event_startdate:"Startzeit",
	event_enddate:"Endzeit",
	event_website:"Website",
	event_image:"Bild",
	event_description:"Beschreibung",
	event_organizer:"Organisator",
	user_profile_company:"Betrieb",
	user_profile_location:"Standort",
	user_profile_jobtitle:"Funktion",
	user_profile_department:"Abteilung",
	user_profile_workdays:"Arbeitstage",
	user_profile_expertise:"Gutachten",
	user_profile_aboutme:"Biographie",
	user_profile_sharedby:"Geteilt von",
	user_profile_phone_short:"T",
	user_profile_fax_short:"F",
	user_profile_email_short:"E",
	user_profile_discover:"entdecken Sie mehr in Delve…",
	news_contactperson:"Ansprechpartner",
	companyarticle_view_also:"Siehe auch",
	companyarticle_documents:"Dokumente",
	companyarticle_events:"Veranstaltungen",
	search_searchresult:"Search results",
	search_filterresult:"Filter results",
	comments_heading:"Comments",
	comments_enter_comment:"Place your comment",
	comments_description_placeholder:"Write a comment",
	comments_not_enabled:"comments are not enabled for this article",
	main_nav_menu:"Menu"
};
