var RRResourcesText = {
	search_placeholder:"Who or what are you looking for?",
	current_connect_placeholder:"What would you like to say?",
	main_nav_current:"Current",
	main_nav_colleagues:"Colleagues",
	main_nav_mycompany:"My company",
	main_nav_royalreesink:"Royal Reesink",
	current_messages_heading:"Current",
	current_messages_load_more:"Load more messages …",
	current_connect_heading:"Connect",
	current_connect_send:"Post a message on Yammer",
	current_connect_others:"What others are saying:",
	current_workfor_heading:"Work at",
	current_vacancies_more:"View all vacancies",
	current_filter:"Filter on:",
	companyprofile_events:"Events",
	companyprofile_alldayevent:"Event lasts all day",
	companyprofile_events_more:"View all events",
	companyprofile_employees:"Who works at this company",
	companyprofile_google_maps:"Calculate the route on Google Maps",
	companyprofile_locations_search:"search for locations …",
	companyprofile_no_locations:"no locations found",
	companyprofile_no_events:"no events found",
	companyprofile_profile:"Profile",
	companyprofile_read_more:"Read more",
	event_company:"Company",
	event_location:"Location",
	event_date:"Date",
	event_startdate:"Start time",
	event_enddate:"End time",
	event_website:"Website",
	event_image:"Image",
	event_description:"Description",
	event_organizer:"Organiser",
	user_profile_company:"Company",
	user_profile_location:"Location",
	user_profile_jobtitle:"Position",
	user_profile_department:"Department",
	user_profile_workdays:"Work days",
	user_profile_expertise:"Expertise",
	user_profile_aboutme:"Biography",
	user_profile_sharedby:"Shared by",
	user_profile_phone_short:"P",
	user_profile_fax_short:"F",
	user_profile_email_short:"E",
	user_profile_discover:"discover more in Delve ...",
	news_contactperson:"Contact person",
	companyarticle_view_also:"View also",
	companyarticle_documents:"Documents",
	companyarticle_events:"Events",
	search_searchresult:"Search results",
	search_filterresult:"Filter results",
	comments_heading:"Comments",
	comments_enter_comment:"Place your comment",
	comments_description_placeholder:"Write a comment",
	comments_not_enabled:"comments are not enabled for this article",
	main_nav_menu:"Menu",
	current_connect_connect_first:"login to Yammer",
	current_connect_loading:"loading messages ..."
};
